-- Seed catalog: ~49 real, publicly known courses/resources across 7 broad domains.
-- Descriptions are original summaries, not copied marketing copy. Run after
-- supabase/migrations/0001_init.sql has been applied.
-- skills_taught / prerequisite_skills are skill tags, not course IDs — the
-- recommendation engine chains courses by matching one course's skills_taught
-- against another's prerequisite_skills (see docs/adr/0003).

insert into courses (title, description, domain, level, duration_hours, skills_taught, prerequisite_skills, source_url) values

-- Programming Fundamentals
('CS50: Introduction to Computer Science', 'Harvard''s broad, project-based tour of computer science — C, algorithms, memory, and data structures from first principles.', 'Programming Fundamentals', 'beginner', 100, ARRAY['programming-fundamentals','c','algorithms'], ARRAY[]::text[], 'https://cs50.harvard.edu/x/'),
('Python for Everybody', 'A gentle, no-assumptions introduction to programming using Python, built around working with real data.', 'Programming Fundamentals', 'beginner', 40, ARRAY['python-basics'], ARRAY[]::text[], 'https://www.py4e.com/'),
('JavaScript Algorithms and Data Structures', 'freeCodeCamp''s hands-on path through core JavaScript syntax, algorithmic thinking, and classic data structures.', 'Programming Fundamentals', 'beginner', 60, ARRAY['javascript-basics','data-structures'], ARRAY[]::text[], 'https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/'),
('Data Structures and Algorithms Specialization', 'A rigorous look at trees, graphs, and algorithmic complexity for learners who already write code comfortably.', 'Programming Fundamentals', 'intermediate', 80, ARRAY['algorithms','data-structures-advanced'], ARRAY['programming-fundamentals'], 'https://www.coursera.org/specializations/data-structures-algorithms'),
('Git and GitHub for Beginners', 'The version-control workflow every other course quietly assumes you already know.', 'Programming Fundamentals', 'beginner', 8, ARRAY['version-control'], ARRAY[]::text[], 'https://www.freecodecamp.org/news/git-and-github-for-beginners/'),
('Object-Oriented Programming in Java', 'Classes, inheritance, and interfaces, taught through building small Java programs.', 'Programming Fundamentals', 'intermediate', 30, ARRAY['oop','java'], ARRAY['programming-fundamentals'], 'https://www.coursera.org/learn/object-oriented-java'),
('Introduction to SQL', 'Querying, filtering, and joining relational data — the baseline skill for almost every data-adjacent course here.', 'Programming Fundamentals', 'beginner', 15, ARRAY['sql-basics'], ARRAY[]::text[], 'https://www.khanacademy.org/computing/computer-programming/sql'),

-- Web Development
('The Odin Project: Full Stack JavaScript', 'A free, project-heavy curriculum covering HTML/CSS through React and Node — the closest thing to a full bootcamp here.', 'Web Development', 'beginner', 300, ARRAY['html-css','javascript-basics','react','nodejs'], ARRAY[]::text[], 'https://www.theodinproject.com/'),
('Responsive Web Design', 'freeCodeCamp''s layout-focused path through semantic HTML and CSS, including Flexbox and Grid.', 'Web Development', 'beginner', 40, ARRAY['html-css'], ARRAY[]::text[], 'https://www.freecodecamp.org/learn/2022/responsive-web-design/'),
('React — The Complete Guide', 'Components, state, and hooks, taught by building progressively larger React applications.', 'Web Development', 'intermediate', 50, ARRAY['react'], ARRAY['javascript-basics'], 'https://react.dev/learn'),
('Node.js, Express, MongoDB & More', 'Building a real backend API — routing, middleware, and a document database — from scratch.', 'Web Development', 'intermediate', 45, ARRAY['nodejs','express','mongodb'], ARRAY['javascript-basics'], 'https://nodejs.org/en/learn'),
('Full Stack Open', 'A demanding, university-grade course covering React, Node, GraphQL, and TypeScript together as one stack.', 'Web Development', 'advanced', 120, ARRAY['react','nodejs','graphql','typescript'], ARRAY['react','nodejs'], 'https://fullstackopen.com/en/'),
('CSS Grid & Flexbox Mastery', 'Layout, properly understood — the two CSS systems that make modern responsive design manageable.', 'Web Development', 'beginner', 12, ARRAY['html-css'], ARRAY[]::text[], 'https://cssgrid.io/'),
('Web Accessibility Fundamentals', 'Designing and building pages that work with screen readers, keyboard navigation, and assistive tech generally.', 'Web Development', 'intermediate', 10, ARRAY['accessibility'], ARRAY['html-css'], 'https://www.w3.org/WAI/fundamentals/'),

-- Data Science & Machine Learning
('Machine Learning Specialization', 'Andrew Ng''s foundational course on supervised and unsupervised learning, with real Python implementation work.', 'Data Science & Machine Learning', 'intermediate', 60, ARRAY['ml-fundamentals'], ARRAY['python-basics'], 'https://www.coursera.org/specializations/machine-learning-introduction'),
('Pandas: Data Manipulation in Python', 'Cleaning, reshaping, and analyzing tabular data — the unglamorous skill underneath every data project.', 'Data Science & Machine Learning', 'beginner', 35, ARRAY['data-analysis','pandas'], ARRAY['python-basics'], 'https://www.kaggle.com/learn/pandas'),
('Deep Learning Specialization', 'Neural networks from the ground up — architectures, training dynamics, and where the intuitions come from.', 'Data Science & Machine Learning', 'advanced', 100, ARRAY['deep-learning','neural-networks'], ARRAY['ml-fundamentals'], 'https://www.coursera.org/specializations/deep-learning'),
('Kaggle: Intro to Machine Learning', 'A short, practical on-ramp to training and evaluating your first models.', 'Data Science & Machine Learning', 'beginner', 5, ARRAY['ml-fundamentals'], ARRAY['python-basics'], 'https://www.kaggle.com/learn/intro-to-machine-learning'),
('Practical Deep Learning for Coders', 'fast.ai''s code-first approach — training real models in week one, theory filled in as it becomes relevant.', 'Data Science & Machine Learning', 'intermediate', 70, ARRAY['deep-learning','pytorch'], ARRAY['python-basics'], 'https://course.fast.ai/'),
('Data Visualization with Python', 'Turning raw analysis into charts people actually understand, using matplotlib and seaborn.', 'Data Science & Machine Learning', 'beginner', 20, ARRAY['data-visualization'], ARRAY['python-basics'], 'https://www.kaggle.com/learn/data-visualization'),
('Natural Language Processing Specialization', 'Text classification, sequence models, and attention — applying deep learning specifically to language.', 'Data Science & Machine Learning', 'advanced', 80, ARRAY['nlp'], ARRAY['deep-learning'], 'https://www.coursera.org/specializations/natural-language-processing'),

-- Cloud & DevOps
('AWS Cloud Practitioner Essentials', 'The vendor-neutral-enough starting point for understanding what "the cloud" actually offers.', 'Cloud & DevOps', 'beginner', 15, ARRAY['cloud-fundamentals','aws'], ARRAY[]::text[], 'https://aws.amazon.com/training/digital/aws-cloud-practitioner-essentials/'),
('Docker for Beginners', 'Packaging an app into a container that runs the same everywhere — the prerequisite for most modern deploys.', 'Cloud & DevOps', 'beginner', 10, ARRAY['containers','docker'], ARRAY[]::text[], 'https://docker-curriculum.com/'),
('Kubernetes Basics', 'Orchestrating many containers at once — pods, deployments, and services, explained without the jargon overload.', 'Cloud & DevOps', 'intermediate', 20, ARRAY['kubernetes','orchestration'], ARRAY['containers'], 'https://kubernetes.io/docs/tutorials/kubernetes-basics/'),
('AWS Solutions Architect Associate', 'Designing resilient, cost-aware infrastructure on AWS, aimed at the industry-standard certification.', 'Cloud & DevOps', 'advanced', 60, ARRAY['aws-architecture'], ARRAY['cloud-fundamentals'], 'https://aws.amazon.com/certification/certified-solutions-architect-associate/'),
('CI/CD with GitHub Actions', 'Automating tests and deploys on every push — the workflow this very project''s PR convention assumes.', 'Cloud & DevOps', 'intermediate', 12, ARRAY['ci-cd'], ARRAY['version-control'], 'https://docs.github.com/en/actions/learn-github-actions'),
('Terraform: Infrastructure as Code', 'Defining cloud infrastructure as versioned, reviewable text instead of manual console clicks.', 'Cloud & DevOps', 'intermediate', 18, ARRAY['iac','terraform'], ARRAY['cloud-fundamentals'], 'https://developer.hashicorp.com/terraform/tutorials'),
('Site Reliability Engineering Fundamentals', 'Google''s own framing of uptime, monitoring, and incident response as an engineering discipline.', 'Cloud & DevOps', 'advanced', 25, ARRAY['sre','monitoring'], ARRAY['cloud-fundamentals'], 'https://sre.google/books/'),

-- Cybersecurity
('Introduction to Cybersecurity', 'The vocabulary and threat landscape every other security course assumes you already have.', 'Cybersecurity', 'beginner', 15, ARRAY['security-fundamentals'], ARRAY[]::text[], 'https://www.cybrary.it/'),
('Google Cybersecurity Certificate', 'A broad, practitioner-oriented path through networks, systems, and the daily work of a security analyst.', 'Cybersecurity', 'beginner', 60, ARRAY['security-fundamentals','network-security'], ARRAY[]::text[], 'https://www.coursera.org/professional-certificates/google-cybersecurity'),
('Ethical Hacking Fundamentals', 'Thinking like an attacker, in a legal lab environment, to understand how systems actually get broken into.', 'Cybersecurity', 'intermediate', 30, ARRAY['penetration-testing'], ARRAY['security-fundamentals'], 'https://www.udemy.com/course/practical-ethical-hacking/'),
('Network Security Basics', 'Firewalls, VPNs, and traffic analysis — securing the network layer specifically.', 'Cybersecurity', 'intermediate', 20, ARRAY['network-security'], ARRAY['security-fundamentals'], 'https://www.cybrary.it/course/network-security'),
('OWASP Top 10 for Web Developers', 'The ten most common web vulnerabilities, and how to not ship them, aimed squarely at people who already build web apps.', 'Cybersecurity', 'intermediate', 8, ARRAY['web-security'], ARRAY['html-css'], 'https://owasp.org/www-project-top-ten/'),
('Cryptography I', 'Stanford''s rigorous introduction to the math and protocols underneath encryption, signatures, and key exchange.', 'Cybersecurity', 'advanced', 25, ARRAY['cryptography'], ARRAY['algorithms'], 'https://www.coursera.org/learn/crypto'),
('Security Operations & Incident Response', 'What happens after the breach — detection, containment, and the process of responding under pressure.', 'Cybersecurity', 'advanced', 30, ARRAY['incident-response'], ARRAY['network-security'], 'https://www.cybrary.it/'),

-- Mobile Development
('Android Basics with Compose', 'Building a first Android app with Kotlin and Jetpack Compose, Google''s current recommended toolkit.', 'Mobile Development', 'beginner', 40, ARRAY['android','kotlin'], ARRAY['programming-fundamentals'], 'https://developer.android.com/courses'),
('iOS App Development with Swift', 'Apple''s own SwiftUI tutorials, building real screens and interactions from the first lesson.', 'Mobile Development', 'beginner', 45, ARRAY['ios','swift'], ARRAY['programming-fundamentals'], 'https://developer.apple.com/tutorials/swiftui'),
('React Native for Cross-Platform Apps', 'Reusing React knowledge to ship one codebase to both iOS and Android.', 'Mobile Development', 'intermediate', 35, ARRAY['react-native'], ARRAY['react'], 'https://reactnative.dev/docs/getting-started'),
('Flutter & Dart: The Complete Guide', 'Google''s cross-platform toolkit, taught through building and styling a complete app.', 'Mobile Development', 'intermediate', 40, ARRAY['flutter','dart'], ARRAY['oop'], 'https://docs.flutter.dev/get-started'),
('Mobile App UX Design', 'Designing for small screens, touch input, and platform-specific conventions before writing any app code.', 'Mobile Development', 'beginner', 15, ARRAY['mobile-ux'], ARRAY[]::text[], 'https://m3.material.io/'),
('Advanced Android Architecture', 'Structuring a large Android app so it stays maintainable — MVVM, modularization, and dependency injection.', 'Mobile Development', 'advanced', 30, ARRAY['android-architecture'], ARRAY['android'], 'https://developer.android.com/topic/architecture'),
('Publishing & Monetizing Mobile Apps', 'What happens after the app is built — store listings, review guidelines, and monetization models.', 'Mobile Development', 'beginner', 8, ARRAY['app-publishing'], ARRAY[]::text[], 'https://developer.android.com/distribute'),

-- UX & Product Design
('Google UX Design Certificate', 'A complete, portfolio-building path through the UX process — research, wireframes, prototypes, and testing.', 'UX & Product Design', 'beginner', 50, ARRAY['ux-fundamentals'], ARRAY[]::text[], 'https://www.coursera.org/professional-certificates/google-ux-design'),
('Figma for UI Design', 'The industry-standard design tool, taught through building real interface components.', 'UX & Product Design', 'beginner', 12, ARRAY['ui-design','figma'], ARRAY[]::text[], 'https://help.figma.com/hu/hc/categories/22132282-Get-started'),
('Design Systems Fundamentals', 'Building reusable component libraries and tokens so a product''s UI stays consistent as it grows.', 'UX & Product Design', 'intermediate', 15, ARRAY['design-systems'], ARRAY['ui-design'], 'https://www.designsystems.com/'),
('User Research Methods', 'Interviews, surveys, and usability studies — figuring out what users actually need versus what they say they want.', 'UX & Product Design', 'intermediate', 18, ARRAY['user-research'], ARRAY['ux-fundamentals'], 'https://www.nngroup.com/articles/which-ux-research-methods/'),
('Interaction Design Specialization', 'How interfaces respond to input over time — motion, feedback, and the feel of a product, not just its layout.', 'UX & Product Design', 'intermediate', 40, ARRAY['interaction-design'], ARRAY['ux-fundamentals'], 'https://www.coursera.org/specializations/interaction-design'),
('Product Management Fundamentals', 'Prioritization, roadmaps, and working with engineering and design as a product owner.', 'UX & Product Design', 'beginner', 20, ARRAY['product-management'], ARRAY[]::text[], 'https://www.coursera.org/professional-certificates/google-project-management'),
('Prototyping & Usability Testing', 'Turning a design into a clickable prototype and watching real people struggle with it before it ships.', 'UX & Product Design', 'intermediate', 15, ARRAY['prototyping','usability-testing'], ARRAY['ui-design'], 'https://www.nngroup.com/articles/usability-testing-101/');
